version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
- name: rene
  coins:
  - 10000token
  - 100000000stake
- name: epicure
  coins:
  - 10000token
  - 100000000stake
- name: horus
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
- name: rene
  bonded: 100000000stake
- name: epicure
  bonded: 100000000stake
- name: horus
  bonded: 100000000stake
